name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
            export CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse
            # the above can be removed once it becomes the default in the future after 1.68 rust
            set -x
            rustc --version
            cargo --version
            cargo fmt --all -- --check
            cargo clippy -- -D warnings
            cargo build
            cargo test
            cargo test --doc
